version: '3.8'
services:
  llm-app-examples:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_VARIANT: ${APP_VARIANT}
    ports:
      - "8080:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true
